# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jr < Formula
  desc "Agent-friendly Jira CLI with structured JSON output and jq filtering"
  homepage "https://github.com/sofq/jira-cli"
  version "0.8.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sofq/jira-cli/releases/download/v0.8.3/jira-cli_0.8.3_darwin_amd64.tar.gz"
      sha256 "78343b333924f089a3ddf0fe1114b2659f395b2d832e6124ef7f29cbe5956fa1"

      define_method(:install) do
        bin.install "jr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sofq/jira-cli/releases/download/v0.8.3/jira-cli_0.8.3_darwin_arm64.tar.gz"
      sha256 "3e9578e8c7e0efe09e950f3f53bbe91421557b970fd64434717fcbbe234177c9"

      define_method(:install) do
        bin.install "jr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofq/jira-cli/releases/download/v0.8.3/jira-cli_0.8.3_linux_amd64.tar.gz"
      sha256 "011ff4094d5d247a54b4733008e4a00811a726ba2cab856b95d9a9fa9bfd1232"
      define_method(:install) do
        bin.install "jr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofq/jira-cli/releases/download/v0.8.3/jira-cli_0.8.3_linux_arm64.tar.gz"
      sha256 "bbd9cf4b58c84f2242293de569fc8895dc9b73e3e5f67f13711562be8a950d88"
      define_method(:install) do
        bin.install "jr"
      end
    end
  end

  test do
    system "#{bin}/jr", "version"
  end
end
