# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jr < Formula
  desc "Agent-friendly Jira CLI with structured JSON output and jq filtering"
  homepage "https://github.com/sofq/jira-cli"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sofq/jira-cli/releases/download/v0.5.2/jira-cli_0.5.2_darwin_amd64.tar.gz"
      sha256 "bdc5ecc6489d3d595704d8bdea37320dc265fe4144749319dfa7883a3448adfd"

      define_method(:install) do
        bin.install "jr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sofq/jira-cli/releases/download/v0.5.2/jira-cli_0.5.2_darwin_arm64.tar.gz"
      sha256 "4bbc59e22067f9619f59a47d3e1d13735fcae41da76a449113087cc282b0b983"

      define_method(:install) do
        bin.install "jr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofq/jira-cli/releases/download/v0.5.2/jira-cli_0.5.2_linux_amd64.tar.gz"
      sha256 "a6af0b1c6a1c7f1fed9c2fc9f96960645976f1835586bdffaf1f3069b5a02c06"
      define_method(:install) do
        bin.install "jr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofq/jira-cli/releases/download/v0.5.2/jira-cli_0.5.2_linux_arm64.tar.gz"
      sha256 "47ca1febc8a3687bc1ea5e9d6331beceee2595822ba11d12700ed52b916d32d6"
      define_method(:install) do
        bin.install "jr"
      end
    end
  end

  test do
    system "#{bin}/jr", "version"
  end
end
