# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jr < Formula
  desc "Agent-friendly Jira CLI with structured JSON output and jq filtering"
  homepage "https://github.com/sofq/jira-cli"
  version "0.8.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sofq/jira-cli/releases/download/v0.8.5/jira-cli_0.8.5_darwin_amd64.tar.gz"
      sha256 "4d4dbfcc42ee4bf84a95315db1c70ed7e64dabae90e36158e6327345f72768b6"

      define_method(:install) do
        bin.install "jr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sofq/jira-cli/releases/download/v0.8.5/jira-cli_0.8.5_darwin_arm64.tar.gz"
      sha256 "0bdc917e62b48f67b0f0173145632d2d6f23b589997d99cb2f1330428c9a09dd"

      define_method(:install) do
        bin.install "jr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofq/jira-cli/releases/download/v0.8.5/jira-cli_0.8.5_linux_amd64.tar.gz"
      sha256 "cbccfcef2f919e90641807b5667abe6ed6f730300b44c1581b0c84f5156e046e"
      define_method(:install) do
        bin.install "jr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofq/jira-cli/releases/download/v0.8.5/jira-cli_0.8.5_linux_arm64.tar.gz"
      sha256 "b20200b32858df10722e579baa071481e60440b26f974a200127f0af06761508"
      define_method(:install) do
        bin.install "jr"
      end
    end
  end

  test do
    system "#{bin}/jr", "version"
  end
end
